# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(350, 330, 379, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.video_type_box_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.video_type_box_2.setObjectName("video_type_box_2")
        self.video_type_box_2.addItem("")
        self.video_type_box_2.addItem("")
        self.horizontalLayout_3.addWidget(self.video_type_box_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.show_video_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.show_video_box.setObjectName("show_video_box")
        self.verticalLayout_3.addWidget(self.show_video_box)
        self.save_video_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.save_video_box.setObjectName("save_video_box")
        self.verticalLayout_3.addWidget(self.save_video_box)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 290, 114, 28))
        self.pushButton.setObjectName("pushButton")
        self.pathText = QtWidgets.QTextBrowser(self.centralwidget)
        self.pathText.setEnabled(False)
        self.pathText.setGeometry(QtCore.QRect(480, 290, 251, 21))
        self.pathText.setStyleSheet("high: 30\n"
"")
        self.pathText.setTabStopWidth(40)
        self.pathText.setObjectName("pathText")
        self.pathText_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.pathText_2.setEnabled(False)
        self.pathText_2.setGeometry(QtCore.QRect(486, 243, 231, 20))
        self.pathText_2.setStyleSheet("high: 30\n"
"")
        self.pathText_2.setTabStopWidth(40)
        self.pathText_2.setObjectName("pathText_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 240, 129, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 440, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.selectFile) # type: ignore
        self.show_video_box.stateChanged['int'].connect(MainWindow.change_if_show_video) # type: ignore
        self.save_video_box.stateChanged['int'].connect(MainWindow.change_if_save_video) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.start) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.selectSavePath) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择视频类型"))
        self.video_type_box_2.setItemText(0, _translate("MainWindow", "航拍视频"))
        self.video_type_box_2.setItemText(1, _translate("MainWindow", "路侧监控视频"))
        self.show_video_box.setText(_translate("MainWindow", "是否展示检测过程"))
        self.save_video_box.setText(_translate("MainWindow", "是否保存检测视频"))
        self.pushButton.setText(_translate("MainWindow", "选择视频文件夹"))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件保存路径"))
        self.pushButton_3.setText(_translate("MainWindow", "开始检测"))
